# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karaage — Cluster account management tool
email: brian@linuxpenguins.xyz
description: > # this means to ignore newlines until "baseurl:"
  Karaage manages users and projects in a cluster and can store the data in
  various backends.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  Karaage-Cluster

# Build settings
markdown: kramdown
